[package]
name = "filess"
version = "0.1.0"
edition = "2024"
description = "Simplified file management"
license = "MIT OR Apache-2.0"

[dependencies]
derive_more = { version = "2.0.1", features = ["from", "deref", "deref_mut", "debug", "as_ref", "from_str", "into_iterator"] }
image = { version = "0.25.9", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
serde_json = { version = "1.0.145", optional = true }
serde_toml = { package = "toml", version = "0.9.11", optional = true, features = ["fast_hash"] }
serde_path_to_error = "0.1.20"
thiserror = "2.0.17"

[features]
# default = []
default = ["serde", "image"]

serde = ["dep:serde", "dep:serde_json", "dep:serde_toml"]
image = ["dep:image"]
